### PR TITLE
Add spec file path to the failed test

### PR DESCRIPTION
**Pull request by msiddique**
- This will add the specfile path to the reports.
- The specfile is captured by scanning the stack trace
Test-Report-specfile

### CODE REVIEW

**Review by stevegibson — APPROVED** [review]
That's a great addition! Thanks for doing it.

**Comment by stevegibson** [comment]
I saw where the spec file wasn't found. Is that a one-off?
image

**Comment by msiddique** [comment]
@stevegibson This is a one-off. This occurs when there aren't any spec files listed in the stack trace.

**Review by domiebett — APPROVED** [review]
Looks like the occasional missing `specFile`s are on errors that we will rarely see on otto server. LGTM. 🙂

**Pull request merged**
